In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a[0]

1

In [5]:
a[1]

2

In [6]:
import time 
import sys

In [7]:
b = range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [8]:
c = np.arange(1000)
print(c.size*c.itemsize)

4000


In [9]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
a.ndim

2

In [11]:
a.itemsize

4

In [12]:
a.shape

(3, 2)

In [13]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [14]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
print("Concartinate String in numpy")
print(np.char.add(["Hello","Hi"], ["Michael" ,"Samuel"]))

Concartinate String in numpy
['HelloMichael' 'HiSamuel']


In [16]:
print(np.char.center("Hello", 20, fillchar=">"))

>>>>>>>Hello>>>>>>>>


In [18]:
print(np.char.capitalize(["hello","hi"]))

['Hello' 'Hi']


In [ ]:
print(np.char.title("hello, hi michael my son"))

Hello, Hi Michael My Son


In [ ]:
print(np.char.lower([["HELLO","HI"], ["MICHAEL" ,"SAMUEL"]]))

[['hello' 'hi']
 ['michael' 'samuel']]


In [ ]:
print(np.char.upper("hello, hi michael my son"))

HELLO, HI MICHAEL MY SON


In [ ]:
print(np.char.split("hello, hi michael my son"))

['hello,', 'hi', 'michael', 'my', 'son']


In [ ]:
print(np.char.splitlines("hello\nhi michael\nmy son"))

['hello', 'hi michael', 'my son']


In [ ]:
print(np.char.strip(["hello", "hi", "michael", "has", "sohn"], "h"))

['ello' 'i' 'michael' 'as' 'sohn']
