<h1 style= "color:red" }>First Import Numpy</h1>

In [49]:
import numpy as np

<h2>The Basics</h2>

In [50]:
a = np.array([1,2,3], dtype="int32")
print(a)

[1 2 3]


In [51]:
b = np.array([[9,8,3,4],[1,8,2,5]])
print(b)

[[9 8 3 4]
 [1 8 2 5]]


In [52]:
# Get dimension which is how many roles the array or data set has
print(b.ndim)
a.ndim

2


1

In [53]:
# Get shape this tell you the shape of the array
print(b.shape)
a.shape

(2, 4)


(3,)

In [54]:
# To get the data type of value stored in the array
print(b.dtype)
a.dtype

int32


dtype('int32')

<h1 style="fontweight: 1000">Accessing & Changing Specific Elements, Rows, Columns, etc</h1>

In [55]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a.shape

(2, 7)

In [56]:
# Get specific element
a[1,5]

13

In [57]:
# Get a specific Row
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [58]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [59]:
# changing a specific number/value in the array
a[1,5] = 29
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 29, 14]])

In [60]:
a[:,-4] = [23,98]
a

array([[ 1,  2,  3, 23,  5,  6,  7],
       [ 8,  9, 10, 98, 12, 29, 14]])

<h2>Initializing Diffrent Types of Array</h2>

In [61]:
# All zero matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
# All 1s matrix
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
# Any other number
np.full((2,4),81)

array([[81, 81, 81, 81],
       [81, 81, 81, 81]])

In [64]:
# {Full_like}
np.full_like(a,12)

array([[12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12]])

In [65]:
# Random decimal number
np.random.rand(3,4)

array([[0.49472189, 0.50428314, 0.105227  , 0.16774477],
       [0.07766617, 0.85469181, 0.06326064, 0.77410093],
       [0.27242475, 0.79000785, 0.38165882, 0.77211516]])

In [66]:
# Random Integer Values
np.random.randint(low=1,high=9, size=(3,3))

array([[5, 3, 5],
       [8, 6, 7],
       [4, 3, 6]])

In [67]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [68]:
z = np.zeros((3,3))
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [69]:
output[1:4,1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

<h1>Mathemactics</h1>

In [73]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [74]:
a + 2

array([3, 4, 5, 6])

In [75]:
a - 2

array([-1,  0,  1,  2])

In [76]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [77]:
b = np.array([4,6,2,9])
b

array([4, 6, 2, 9])

In [78]:
a + b

array([ 5,  8,  5, 13])